export const scaleFactor = 4;

export const dialogueData = {
    alien_report: `<a href="./Projects/data_science/UFOsightings.pptx" target="_blank">Follow this link</a> to download a power point investigating alien sightings in America!`,
    hacker_news: `Want to know the best time to post to hacker News?  <a href="https://github.com/evanhinton/evanhinton/blob/8675c6b411d22e3803808ce7511f14bc139ab0e8/Hacker_news_post_analysis.ipynb" target="_blank">Look no further</a>!`,
    app_profile: `<a href="https://github.com/evanhinton/evanhinton/blob/8675c6b411d22e3803808ce7511f14bc139ab0e8/App_Profile_from_apple_store_and_google_play.ipynb" target="_blank">This report</a> looks into the most popular types of apps on the App Store and Google Play`,
    ml_project: `This is an introductory <a href="https://github.com/evanhinton/evanhinton/blob/8675c6b411d22e3803808ce7511f14bc139ab0e8/gradientboostedtrees.ipynb" target="_blank">Machine Learning project</a> using Gradient Boosted Trees`,
    computer: `Here are the websites I designed/manage: <ul>
                <li><a href="https://russellwalkercomposer.com/" target="_blank">russellwalkercomposer.com</a></li>
                <li><a href="https://thedetweilers.com/" target="_blank">thedetweilers.com</a></li>
                </ul>
                For a full list of projects please visit my static portfolio page <a href="./Projects/web_dev/practice_portfolio/index.html" target="_blank">here</a>, or visit my github repo <a href="" target="_blank">here</a> for all projects and code. <br/><br/>About: <br/><br/>Born in Owen Sound, Ontario in 1991; I spent the first year of my life toiling on a farm before we packed up and moved to the big city (Toronto) for work.  At the age of 3, I had already mastered the ability to be a complete nuisance to my parents while being an absolute angel to our neighbor so she would give my brother and I raspberries she grew.  <br/><br/>As time went on I decided to get older, eventually finding myself thriving in the Electromagnetic Engineering Technician course at George Brown College.  I had a great time learning how to program PLC's and arduinos and learning the basics of electric and hydrolic circuits.  My interest was piqued after taking a physics class, so after I graduated I went back to high school to improve my grades then enrolled in the University of Toronto, where I eventually earned a Physics Specialist Degree.  <br/><br/>Since then I have been building up my technical skill set by learning various computer languages and improving upon my statistics and data analysis techniques.  I have spent the last 2 years working as a Software Tester for plato, building on my troubleshooting and investigative experience.  <br/><br/>Thank you for reading!`,
    drum_machine: `Check out this <a href="./Projects/web_dev/drum_machine/index.html" target="_blank">Drum Machine</a> made using React!`,
    bar_chart: `Here is a <a href="./Projects/web_dev/bar_chart/index.html" target="_blank">bar chart</a> made using the D3 visualization library.`,
    band_logo: `Created this <a href="./Projects/web_dev/detweilers_logo/index.html" target = "_blank">band logo</a> using SCSS and the box shadow property, check out the code <a href="" target="_blank">here</a>`,
    random_quote: `Need some inspiration? Here is a collection of <a href="./Projects/web_dev/random_quote/index.html" target="_blank">quotes</a>.`,
    survey_form: `<a href="./Projects/web_dev/survey_form/index.html" target="_blank">Survey Form</a>`,
    tribute_page: `<a href="./Projects/web_dev/tribute_page/index.html" target="_blank">Tribute Page</a>`,
    product_landing: `<a href="./Projects/web_dev/product_landing/index.html" target="_blank">product landing page</a>`,
    technical_document: `<a href="./Projects/web_dev/technical_document/index.html" target="_blank">Technical Document</a>`,
    practice_portfolio: `<a href="./Projects/web_dev/practice_portfolio/index.html" target="_blank">Practice Portfolio</a>`,
    markdown_previewer: `<a href="./Projects/web_dev/markdown_previewer/index.html" target="_blank">Markdown Previewer</a>`,
    exit: `Return to <a href="./index.html">Static website</a>?`,
    host: 'Hello and welcome!  Please make yourself at home.  First I just wanted to thank you for taking the time to visit and check out my work!  <br/><br/>There are two rooms, this room highlights my web developement work and the other room highlights my data science work, while this map highlights my game developement work.  The icons on the carpet showcase some of my projects and are accessible by walking to them.  <br/><br/>The door on my right here exits back to the conventional portfolio website with all the same information; as people with accessibility needs may have a hard time interacting with this map.  The computer in the corner has links to a couple websites I manage and a link to the github repo where all the projects and code are stored, plus a short bio.  <br/><br/>Finally, Hootnoot just below me will acknowledge all the lessons and software I used to create my portfolio.  Happy Exploring!',
    hootnoot: `HOOTNOOOOOOOOT... ahem... my apologies.  Greetings fine traveller!  Here I would like to acknowledge the work of other developers that Evan used to build this portfolio. 
               <br></br> First I would like to thank JSLegendDev‬ for his youtube course on building a 2D portfolio site, found <a href="https://www.youtube.com/watch?v=wy_fSStEgMs" target="_blank">here</a>
               <br></br> Next a big thanks to Thorbjørn Lindeijer for his <a href="https://www.mapeditor.org/" target="_blank">Tiled</a> software, which made building game maps incredibly easy.
               `
}